Thinkdocs 85 update variable section
thinkcompany/think_dev-standards pull request #11
Opened 2022-03-01 17:32 UTC by arwehrman

## Changes

- removes all instances of `var` and replaces them with `let` or `const` in the JS section   
- updates variable subsection of the JS section with `let` and `const` usage 

## Checklist

Mark any that apply to this PR

- [ ] Requires dependency update?
- [ ] Pass accessibility
- [ ] Automated tests
- [ ] Looks good on mobile

## Tickets Closed

List closed tickets below

- Closes [THINKDOCS-85](https://thinkcompany.atlassian.net/browse/THINKDOCS-85?atlOrigin=eyJpIjoiNjIxYmRlN2I1M2E0NDE4ODk0MTA2YWUwMDA4NGQwNmYiLCJwIjoiaiJ9)

2022-03-02 17:04 UTC, brendanmckeown requested changes
We should use `const` in the examples, unless the reference is being redefined.

2022-03-02 17:04 UTC, brendanmckeown commented on content/javascript/general-authoring/index.md
> +const bar = foo;
Since we are changing the value of `bar`, it should use `let` instead of `const`.
```suggestion
let bar = foo;
```

2022-03-02 17:04 UTC, brendanmckeown commented on content/javascript/general-authoring/index.md
> +let item = new Object();
These examples can use `const` since they are not being redefined.
```suggestion
const item = new Object();
```

2022-03-02 17:04 UTC, brendanmckeown commented on content/javascript/general-authoring/index.md
>  Don't use [reserved words](http://es5.github.io/#x7.6.1) as keys. It won't work in IE8. [More info](https://github.com/airbnb/javascript/issues/61).
This looks like a more complete list of reserved keywords:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#reserved_keywords_as_of_ecmascript_2015

```suggestion
Don't use [reserved words](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#reserved_keywords_as_of_ecmascript_2015) as keys. It won't work in IE8. [More info](https://github.com/airbnb/javascript/issues/61).
```

2022-03-02 17:04 UTC, brendanmckeown commented on content/javascript/general-authoring/index.md
>  Don't use [reserved words](http://es5.github.io/#x7.6.1) as keys. It won't work in IE8. [More info](https://github.com/airbnb/javascript/issues/61).
Sorry, this comment is out of scope for the story.

2022-03-02 17:04 UTC, brendanmckeown commented on content/javascript/general-authoring/index.md
> +Always use `let` or `const` to declare variables. Use `let` for variables that need to mutable. Be sure to declare `let` at the top of the scope in which they are used.  The preference is to use `con
```suggestion
Always use `let` or `const` to declare variables. Use `let` for variables that need to mutable. Be sure to declare `let` at the top of the scope in which they are used. The preference is to use `const` when possible. A variable declared with `const` is immutable (i.e. it cannot be redefined). When creating objects or arrays using `const`, keep in mind that modifying the items _inside_ the object does not mutate the object reference itself. [Read More about using `const` here.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const)
```

2022-03-07 14:48 UTC, arwehrman commented on content/javascript/general-authoring/index.md
>  Don't use [reserved words](http://es5.github.io/#x7.6.1) as keys. It won't work in IE8. [More info](https://github.com/airbnb/javascript/issues/61).
No worries, I'm going to update it anyway.

2022-03-07 21:52 UTC, brendanmckeown approved these changes

2022-03-10 22:32 UTC, THoj13 commented on content/javascript/general-authoring/index.md
> +s
Could this `s` be removed?

2022-03-18 14:43 UTC, THoj13 approved these changes

2022-05-03 13:13 UTC, merged